runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/Swarzox/test.git#d4b09016443c2c3efd6597aa3610c2e0bbac0d05'
env_variables:
  'ENDPOINTS_SERVICE_NAME': 'web-cloud-datastore-363112'
api_version: 'user_defined'
handlers:
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.jsx)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.js)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/.*\.html)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: /
  script: unused
  login: optional
  secure: optional
- url: /upload
  script: unused
  login: optional
  secure: optional
- url: /serve
  script: unused
  login: optional
  secure: optional
- url: /disconnection
  script: unused
  login: optional
  secure: optional
- url: /connection
  script: unused
  login: optional
  secure: optional
- url: /thecount
  script: unused
  login: optional
  secure: optional
- url: /.*/
  script: unused
  login: optional
  secure: optional
- url: /_ah/.*
  script: unused
  login: optional
  secure: optional
- url: /followUser
  script: unused
  login: optional
  secure: optional
